# Name of the action visible in the action overview
name: Figma release
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    type: Figma-release
env:
  payload: ${{toJSON(github.event.client_payload.release)}}
jobs:
  build:
    # the name for the entire job
    name: Transform Figma design tokens for specific platforms
    # we run this on ubuntu, leave this alone, if you don't have a good reason to change it
    runs-on: ubuntu-latest
    steps:
      # this lets us work in the actual repository 
      - uses: actions/checkout@master
      # if the folder named "tokens" does not exist, create it
      - name: mkdir "releases" directory
        # change tokens here (and in line 32) if you want to use a differently named folder 
        run: 'mkdir -p releases'
      # this creates a json file from the stringified json from the request body
      - uses: devops-actions/json-to-file@v1.0.0
        with:
          json: |
            ${{ github.event.client_payload.release }}
          filename: "releases/${{ env.payload.file_name }}.json"
      # we now initialize node to run amazon style dictionary to compile the tokens
      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v1
      #   with:
      #     # we use version 14.x of node
      #     node-version: 14.x
      # # We now run npm i to install all dependencies and run the "transfrom" script that is defined in the package.json (change this if you need to)
      # - name: Transform design tokens 
      #   run: 'npm i && npm run transform-tokens'
      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "New Figma Release"
          title: "New Figma Release"
          body: "New Figma Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this parameter is optional and defaults to master but I am using main
          BRANCH_NAME: 'main'